version: '3'

services:
  app.monolith:
    container_name: app.monolith
    ports:
      - "8000:8000"
    build:
      context: ./src
      dockerfile: Dockerfile
    networks:
      - xampp8

  db.phpmyadmin:
        image: phpmyadmin
        ports:
          - "3030:80"
        environment:
          - PMA_HOST=db.mysql
          - PMA_PORT=3306
        networks:
          - xampp8
  db.mysql:
        container_name: db.mysql
        build:
          context: ./dockers/mysql
          dockerfile: Dockerfile
        ports:
          - "3306:3306"
        volumes:
            - ./volumes/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
        networks:
            - xampp8

networks:
      xampp8:
        driver: bridge