version: '3'
services:

  db.mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - './volumes/db/mongodb/main:/data/db'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - pv121_network
    env_file:
      - .env

  db.mysql.main:
    image: 'mysql/mysql-server:latest'
    ports:
      - '33121:3306'
    volumes:
      - './volumes/db/mysql/main:/var/lib/mysql'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - pv121_network
    env_file:
      - .env

  node.api.auth:
    build: ./node_api_auth
    volumes:
      - ./node_api_auth:/usr/src/app
    command: sh -c " npm install && npm start "
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - pv121_network
    environment:
      - NAME=NodeApiAuth
    env_file:
      - .env

  node.api.horoscope:
    build: ./node_api_horoscope
    volumes:
      - ./node_api_horoscope:/usr/src/app
    command: sh -c " npm install && npm start "
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - pv121_network
    environment:
      - NAME=NodeApiHoroscope
    env_file:
      - .env

  node.api:
    build: ./node_api
    volumes:
      - ./node_api:/usr/src/app
    command: sh -c " npm install && npm start "
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - pv121_network
    ports:
      - "3000:3000"
    environment:
      - NAME=NodeApi
    env_file:
      - .env


  front.api:
    build: ./front_api
    volumes:
      - ./front_api:/usr/src/app
    command: sh -c " npm install && npm start "
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - pv121_network
    ports:
      - "5173:5173"
    environment:
      - NAME=FrontApi
    env_file:
      - .env


  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - pv121_network
    ports:
      - "80:80"
    depends_on:
      - front.api
      - node.api
      - node.api.horoscope
      - node.api.auth




networks:
  pv121_network:
    driver: bridge